Update CI.yaml

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -77,17 +77,17 @@ jobs:
         set -eE -o functrace
         
         failure() {
-          local lineno=$2
-          local fn=$3
-          local exitstatus=$4
-          local msg=$5
-          local lineno_fns=${1% 0}
-          if [[ "$lineno_fns" != "0" ]] ; then
-            lineno="${lineno} ${lineno_fns}"
+          local lineno=\$2
+          local fn=\$3
+          local exitstatus=\$4
+          local msg=\$5
+          local lineno_fns=\${1% 0}
+          if [[ "\$lineno_fns" != "0" ]] ; then
+            lineno="\${lineno} \${lineno_fns}"
           fi
-          echo "${BASH_SOURCE[1]}:${fn}[${lineno}] Failed with status ${exitstatus}: $msg"
+          echo "\${BASH_SOURCE[1]}:\${fn}[\${lineno}] Failed with status \${exitstatus}: \$msg"
         }
-        trap 'failure "${BASH_LINENO[*]}" "$LINENO" "${FUNCNAME[*]:-script}" "$?" "$BASH_COMMAND"' ERR
+        trap 'failure "\${BASH_LINENO[*]}" "\$LINENO" "\${FUNCNAME[*]:-script}" "\$?" "\$BASH_COMMAND"' ERR
         ##############################################################################################
         apt update;
         apt install ca-certificates curl gnupg lsb-release software-properties-common wget git vagrant python3-venv direnv python3-pip linux-headers-\$(uname -r) ansible -y;
